# Configuración para GitHub Pages con subcarpeta

# Si tu sitio está en una subcarpeta (ej: /prototype)
# Agrega esto a tu HTML o usa un archivo _config.yml

baseurl: "/revistalogos"
url: "https://tu-usuario.github.io"
