# Configuración para GitHub Pages con subcarpeta

# Si tu sitio está en una subcarpeta (ej: /prototype)
# Agrega esto a tu HTML o usa un archivo _config.yml

baseurl: "/demo-revistalogos"
url: "https://refo44.github.io"
